import LegalLayout from '@/components/LegalLayout';

export default function Disclaimer() {
  return (
    <LegalLayout icon="disclaimer" title="Disclaimer" lastUpdated="August 12, 2026">
      <p>
        The information provided by ApplicationWala on this website is for general informational
        purposes only. All information is provided in good faith; however, we make no representation
        or warranty of any kind regarding the accuracy, adequacy, validity, reliability, or
        completeness of any information on this site.
      </p>

      <h2>Generated Application Letters</h2>
      <p>
        The bank application letters generated by our tool are based on commonly used standard
        formats. These letters are provided as templates to assist you in drafting your own
        application. Different banks — including SBI, HDFC, PNB, ICICI, and others — may have their
        own prescribed formats, forms, and requirements. We strongly recommend verifying with your
        bank branch before submitting any application.
      </p>

      <h2>No Affiliation with Any Bank</h2>
      <p>
        ApplicationWala is an independent tool and is not affiliated with, endorsed by, or
        associated with any bank, financial institution, or government body. All bank names
        mentioned on this website are for informational and reference purposes only and belong to
        their respective owners.
      </p>

      <h2>Not Professional Advice</h2>
      <p>
        Under no circumstance shall we constitute any legal, financial, or professional advice. Any
        reliance you place on such information is strictly at your own risk. We recommend consulting
        with your bank or a qualified professional for advice tailored to your specific situation.
      </p>

      <h2>External Links</h2>
      <p>
        Our website may contain links to external websites that are not provided or maintained by us.
        We do not guarantee the accuracy, relevance, timeliness, or completeness of any information
        on these external websites.
      </p>

      <h2>Advertisement Disclaimer</h2>
      <p>
        This website displays third-party advertisements through Google AdSense and other ad
        networks. We do not control the content of these ads and are not responsible for any claims
        made by advertisers. The presence of an ad does not constitute an endorsement.
      </p>

      <h2>Limitation of Liability</h2>
      <p>
        In no event will ApplicationWala be liable for any loss or damage arising from the use of
        this website or the content generated by our tool. Your use of the website and its content
        is solely at your own risk.
      </p>

      <h2>Consent</h2>
      <p>
        By using our website, you hereby consent to this disclaimer and agree to its terms.
      </p>
    </LegalLayout>
  );
}
