import LegalLayout from '@/components/LegalLayout';

export default function TermsConditions() {
  return (
    <LegalLayout icon="terms" title="Terms &amp; Conditions" lastUpdated="August 12, 2026">
      <p>
        Welcome to ApplicationWala. By accessing and using this website, you accept and agree to be
        bound by these Terms and Conditions. If you do not agree with any part of these terms,
        please do not use our website.
      </p>

      <h2>Use of the Service</h2>
      <p>
        ApplicationWala provides a free online tool to generate bank application letters in English
        and Hindi. The tool is intended for personal and lawful use only. You agree not to use the
        service for any illegal or unauthorized purpose.
      </p>

      <h2>No Warranty of Accuracy</h2>
      <p>
        The application letters generated by this tool are based on standard formats and are provided
        for general informational purposes only. We do not guarantee that any specific bank will
        accept the generated letter in its current form. Banks may have their own prescribed formats
        and requirements. You are responsible for verifying the accuracy and completeness of the
        content before submission.
      </p>

      <h2>Not Legal or Financial Advice</h2>
      <p>
        The content on this website, including the Banking Guide articles and generated letters,
        does not constitute legal, financial, or professional advice. Always consult with your bank
        or a qualified professional for specific guidance regarding your banking matters.
      </p>

      <h2>Intellectual Property</h2>
      <p>
        All content on this website, including text, design, logos, and software, is the property of
        ApplicationWala or its content creators and is protected by applicable intellectual property
        laws. You may not reproduce, distribute, or create derivative works without our prior written
        consent.
      </p>

      <h2>Third-Party Advertisements</h2>
      <p>
        This website displays advertisements served by third-party advertising networks such as
        Google AdSense. We are not responsible for the content of these advertisements or any
        products or services advertised. Clicking on ads is at your own risk.
      </p>

      <h2>Limitation of Liability</h2>
      <p>
        ApplicationWala shall not be liable for any direct, indirect, incidental, consequential, or
        punitive damages arising from your use of the website or the generated application letters.
      </p>

      <h2>Changes to Terms</h2>
      <p>
        We reserve the right to modify these Terms and Conditions at any time. Continued use of the
        website after changes constitutes acceptance of the new terms.
      </p>

      <h2>Contact</h2>
      <p>
        For any questions regarding these Terms and Conditions, please reach out via our Contact Us
        page.
      </p>
    </LegalLayout>
  );
}
